"""add init

Revision ID: 3160670fade9
Revises: 
Create Date: 2025-11-14 17:10:31.512331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3160670fade9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boq_categories',
    sa.Column('boq_category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('boq_category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_boq_categories_boq_category_id'), 'boq_categories', ['boq_category_id'], unique=False)
    op.create_table('item_categories',
    sa.Column('item_category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('item_category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_item_categories_item_category_id'), 'item_categories', ['item_category_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_table('benchmark_materials',
    sa.Column('benchmark_material_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quality_standard', sa.String(length=100), nullable=True),
    sa.Column('default_quantity_per_m3', sa.Numeric(), nullable=True, comment='For solid materials: default usage per m3'),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('default_wastage_multiplier', sa.Numeric(), server_default='1.0', nullable=True),
    sa.Column('dimensions', sa.Numeric(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True, comment='For liquid materials: numeric amount (with unit like L/kg)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('required_by', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.item_category_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('benchmark_material_id')
    )
    op.create_index(op.f('ix_benchmark_materials_benchmark_material_id'), 'benchmark_materials', ['benchmark_material_id'], unique=False)
    op.create_table('project_gmail_tokens',
    sa.Column('project_gmail_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expiry', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_gmail_id')
    )
    op.create_index(op.f('ix_project_gmail_tokens_project_gmail_id'), 'project_gmail_tokens', ['project_gmail_id'], unique=False)
    op.create_table('rule_sets',
    sa.Column('rule_set_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_set_id')
    )
    op.create_index(op.f('ix_rule_sets_rule_set_id'), 'rule_sets', ['rule_set_id'], unique=False)
    op.create_table('boq',
    sa.Column('boq_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('rule_set_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.rule_set_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('boq_id')
    )
    op.create_index(op.f('ix_boq_boq_id'), 'boq', ['boq_id'], unique=False)
    op.create_table('rule_items',
    sa.Column('rule_item_id', sa.Integer(), nullable=False),
    sa.Column('rule_set_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.rule_set_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_item_id')
    )
    op.create_index(op.f('ix_rule_items_rule_item_id'), 'rule_items', ['rule_item_id'], unique=False)
    op.create_table('boq_items',
    sa.Column('boq_item_id', sa.Integer(), nullable=False),
    sa.Column('boq_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('standard', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['boq_id'], ['boq.boq_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['boq_categories.boq_category_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('boq_item_id')
    )
    op.create_index(op.f('ix_boq_items_boq_item_id'), 'boq_items', ['boq_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boq_items_boq_item_id'), table_name='boq_items')
    op.drop_table('boq_items')
    op.drop_index(op.f('ix_rule_items_rule_item_id'), table_name='rule_items')
    op.drop_table('rule_items')
    op.drop_index(op.f('ix_boq_boq_id'), table_name='boq')
    op.drop_table('boq')
    op.drop_index(op.f('ix_rule_sets_rule_set_id'), table_name='rule_sets')
    op.drop_table('rule_sets')
    op.drop_index(op.f('ix_project_gmail_tokens_project_gmail_id'), table_name='project_gmail_tokens')
    op.drop_table('project_gmail_tokens')
    op.drop_index(op.f('ix_benchmark_materials_benchmark_material_id'), table_name='benchmark_materials')
    op.drop_table('benchmark_materials')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_item_categories_item_category_id'), table_name='item_categories')
    op.drop_table('item_categories')
    op.drop_index(op.f('ix_boq_categories_boq_category_id'), table_name='boq_categories')
    op.drop_table('boq_categories')
    # ### end Alembic commands ###
