"""add email table

Revision ID: a68f07bef6c0
Revises: 3160670fade9
Create Date: 2025-11-14 17:22:31.837087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a68f07bef6c0'
down_revision: Union[str, None] = '3160670fade9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('mail_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attachments_url', sa.Text(), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mail_id')
    )
    op.create_index(op.f('ix_emails_mail_id'), 'emails', ['mail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_mail_id'), table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
