"""add vendors and rfqs

Revision ID: b6217cf0ddc2
Revises: bcbd3ea33fbe
Create Date: 2025-11-15 12:36:01.725722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b6217cf0ddc2'
down_revision: Union[str, None] = 'bcbd3ea33fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benchmark_materials', sa.Column('amount', sa.Numeric(), nullable=True))
    op.add_column('benchmark_materials', sa.Column('basis', sa.Enum('per_m3', 'per_m2', 'per_m', 'per_unit', 'absolute', name='benchmark_basis_enum'), nullable=True))
    op.drop_column('benchmark_materials', 'quantity')
    op.drop_column('benchmark_materials', 'default_quantity_per_m3')
    op.add_column('boq', sa.Column('pdf_link', sa.String(length=255), nullable=True))
    op.add_column('boq', sa.Column('compute_json', sa.Text(), nullable=True))
    op.alter_column('rule_items', 'rule_set_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rule_items', 'key',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('rule_items', 'unit',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
    op.drop_index(op.f('ix_rule_items_rule_item_id'), table_name='rule_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rule_items_rule_item_id'), 'rule_items', ['rule_item_id'], unique=False)
    op.alter_column('rule_items', 'unit',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('rule_items', 'key',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('rule_items', 'rule_set_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('boq', 'compute_json')
    op.drop_column('boq', 'pdf_link')
    op.add_column('benchmark_materials', sa.Column('default_quantity_per_m3', sa.NUMERIC(), autoincrement=False, nullable=True, comment='For solid materials: default usage per m3'))
    op.add_column('benchmark_materials', sa.Column('quantity', sa.NUMERIC(), autoincrement=False, nullable=True, comment='For liquid materials: numeric amount (with unit like L/kg)'))
    op.drop_column('benchmark_materials', 'basis')
    op.drop_column('benchmark_materials', 'amount')
    # ### end Alembic commands ###
