"""added new table

Revision ID: c927aa16fe12
Revises: 187714a9ee44
Create Date: 2025-11-14 13:24:19.071174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c927aa16fe12'
down_revision: Union[str, None] = '187714a9ee44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'project_gmail_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),  # Change UUID to Integer if projects.project_id is Integer
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('access_token', sa.Text(), nullable=False),
        sa.Column('refresh_token', sa.Text(), nullable=False),
        sa.Column('token_expiry', sa.TIMESTAMP(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
        sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_project_gmail_tokens_id'), 'project_gmail_tokens', ['id'], unique=False)
    op.add_column('workflows', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workflows', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'user_id')
    op.drop_index(op.f('ix_project_gmail_tokens_id'), table_name='project_gmail_tokens')
    op.drop_table('project_gmail_tokens')
    # ### end Alembic commands ###
